# Generated by Django 4.2.7 on 2025-04-19 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('minecraft_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicMapPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('point_type', models.CharField(choices=[('town', 'Ville'), ('capital', 'Capitale'), ('warp', 'Point de téléportation'), ('shop', 'Magasin'), ('pve', 'Zone PvE'), ('pvp', 'Zone PvP')], max_length=20)),
                ('location_x', models.IntegerField(help_text='Coordonnée X sur la carte')),
                ('location_z', models.IntegerField(help_text='Coordonnée Z sur la carte')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('leader', models.CharField(max_length=100)),
                ('founded_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('capital', models.CharField(max_length=100)),
                ('flag_image', models.CharField(blank=True, help_text="URL de l'image du drapeau", max_length=255, null=True)),
                ('real_world_country', models.CharField(blank=True, help_text='Pays réel représenté', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.CharField(blank=True, help_text="URL de l'image", max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('color_code', models.CharField(help_text='Code couleur HEX (ex: #FF0000)', max_length=7)),
                ('is_donation', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('mod', 'Modérateur'), ('helper', 'Helper'), ('builder', 'Builder')], max_length=20)),
                ('minecraft_uuid', models.CharField(blank=True, max_length=36, null=True)),
                ('description', models.TextField(blank=True)),
                ('discord_username', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mayor', models.CharField(max_length=100)),
                ('founded_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('residents_count', models.IntegerField(default=1)),
                ('location_x', models.IntegerField(help_text='Coordonnée X sur la carte')),
                ('location_z', models.IntegerField(help_text='Coordonnée Z sur la carte')),
                ('real_world_location', models.CharField(blank=True, help_text='Lieu réel représenté', max_length=100)),
                ('nation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='towns', to='minecraft_app.nation')),
            ],
        ),
        migrations.CreateModel(
            name='TownyServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='GeoMC - Earth Towny', max_length=100)),
                ('ip_address', models.CharField(default='play.geomc.fr', max_length=100)),
                ('description', models.TextField(default="Serveur Towny sur une carte de la Terre à l'échelle 1:1000")),
                ('version', models.CharField(default='1.20.4', max_length=20)),
                ('player_count', models.IntegerField(default=0)),
                ('max_players', models.IntegerField(default=100)),
                ('status', models.BooleanField(default=True)),
                ('discord_link', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Towny Server',
            },
        ),
        migrations.DeleteModel(
            name='MinecraftServer',
        ),
    ]
