# Generated by Django 4.2.7 on 2025-04-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft_app', '0002_dynamicmappoint_nation_newspost_rank_serverrule_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsPost',
        ),
    ]
