# Generated by Django 4.2.7 on 2025-04-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft_app', '0003_remove_newspost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicmappoint',
            name='location_x',
            field=models.IntegerField(help_text='X coordinate on the map'),
        ),
        migrations.AlterField(
            model_name='dynamicmappoint',
            name='location_z',
            field=models.IntegerField(help_text='Z coordinate on the map'),
        ),
        migrations.AlterField(
            model_name='dynamicmappoint',
            name='point_type',
            field=models.CharField(choices=[('town', 'Town'), ('capital', 'Capital'), ('warp', 'Teleport Point'), ('shop', 'Shop'), ('pve', 'PvE Zone'), ('pvp', 'PvP Zone')], max_length=20),
        ),
        migrations.AlterField(
            model_name='nation',
            name='flag_image',
            field=models.CharField(blank=True, help_text='URL of the flag image', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nation',
            name='real_world_country',
            field=models.CharField(blank=True, help_text='Real world country represented', max_length=100),
        ),
        migrations.AlterField(
            model_name='rank',
            name='color_code',
            field=models.CharField(help_text='HEX color code (e.g.: #FF0000)', max_length=7),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('mod', 'Moderator'), ('helper', 'Helper'), ('builder', 'Builder')], max_length=20),
        ),
        migrations.AlterField(
            model_name='town',
            name='location_x',
            field=models.IntegerField(help_text='X coordinate on the map'),
        ),
        migrations.AlterField(
            model_name='town',
            name='location_z',
            field=models.IntegerField(help_text='Z coordinate on the map'),
        ),
        migrations.AlterField(
            model_name='town',
            name='real_world_location',
            field=models.CharField(blank=True, help_text='Real world location represented', max_length=100),
        ),
        migrations.AlterField(
            model_name='townyserver',
            name='description',
            field=models.TextField(default='Towny server on a 1:1000 scale Earth map'),
        ),
    ]
