# Generated by Django 4.2.7 on 2025-04-21 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('minecraft_app', '0004_alter_dynamicmappoint_location_x_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minecraft_username', models.CharField(blank=True, max_length=100)),
                ('minecraft_uuid', models.CharField(blank=True, max_length=36)),
                ('bio', models.TextField(blank=True)),
                ('discord_username', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
