# Generated by Django 4.2.7 on 2025-04-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft_app', '0006_userpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='townyserver',
            name='ip_address',
            field=models.CharField(default='play.Novania.fr', max_length=100),
        ),
        migrations.AlterField(
            model_name='townyserver',
            name='name',
            field=models.CharField(default='Novania - Earth Towny', max_length=100),
        ),
    ]
