# Generated by Django 4.2.7 on 2025-04-25 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('minecraft_app', '0007_alter_townyserver_ip_address_alter_townyserver_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.CharField(blank=True, help_text='URL of the item image', max_length=255, null=True)),
                ('color_code', models.CharField(help_text='HEX color code (e.g.: #FF0000)', max_length=7)),
                ('category', models.CharField(choices=[('collectible', 'Collectible'), ('cosmetic', 'Cosmetic'), ('utility', 'Utility'), ('special', 'Special')], default='collectible', max_length=20)),
                ('quantity', models.IntegerField(default=1, help_text='Available quantity (-1 for unlimited)')),
            ],
        ),
        migrations.CreateModel(
            name='StoreItemPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_id', models.CharField(max_length=100)),
                ('payment_status', models.CharField(default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='minecraft_app.storeitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_item_purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='minecraft_app.rank')),
                ('store_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='minecraft_app.storeitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'rank'), ('user', 'store_item')},
            },
        ),
    ]
