# Generated by Django 4.2.7 on 2025-04-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft_app', '0008_storeitem_storeitempurchase_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('session_id', models.CharField(max_length=100)),
                ('error_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
