# Generated by Django 4.2.7 on 2025-04-26 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('minecraft_app', '0009_webhookerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpurchase',
            name='gifted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifts_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpurchase',
            name='is_gift',
            field=models.BooleanField(default=False),
        ),
    ]
