# Generated by Django 4.2.7 on 2025-05-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft_app', '0011_rank_features_alter_userpurchase_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='kit_image',
            field=models.CharField(blank=True, help_text='URL of the kit image', max_length=255, null=True),
        ),
    ]
