# Generated by Django 4.2.7 on 2025-05-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft_app', '0012_rank_kit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='kit_image',
            field=models.CharField(blank=True, help_text='Path to the kit image in static/images folder (e.g.: ranks/vip_kit.png)', max_length=255, null=True),
        ),
    ]
