# Generated by Django 4.2.7 on 2025-05-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft_app', '0013_alter_rank_kit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
