# Generated by Django 4.2.7 on 2025-05-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft_app', '0014_cartitem_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='townyserver',
            name='version',
            field=models.CharField(default='1.21.4+', max_length=20),
        ),
    ]
